### ISSUE TITLE
`connect_athena` requires a value for `staging_dir` in `v0.5.0`

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [moj-analytical-services/Rdbtools#30]
Up to and including version `v0.4.0`, `staging_dir = NULL` was the default. From version `v0.5.0`, a non-empty value is required for this argument, otherwise access to the data sets is denied. See https://github.com/ministryofjustice/data-platform-support/issues/699

Having to specify the bucket in the staging directory argument for each and every dataset feels like overkill. Was this change intentional?

**Comment by pjrh-moj** [comment]
This isn't the intended behaviour, and isn't how it works for me.  It looks like there may be a bug here, but it is more complicated than just the way `Rdbtools` handles the staging dir...

I am unable to replicate this

**Comment by andreassoteriadesmoj** [comment]
Version [`0.5.2`](https://github.com/moj-analytical-services/Rdbtools/releases/tag/v0.5.2) seems to have resolved this issue. 

(Some context: https://mojdt.slack.com/archives/C1PUCG719/p1718895990626449?thread_ts=1718876600.993429&cid=C1PUCG719)
